name: Build and Deploy Docker Image to AWS Lambda

on:
  push:
    branches:
      - prod  # Trigger workflow on push to main branch
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Log in to DockerHub or Amazon ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t yann-fan ./backend

      # Tag the Docker image
      - name: Tag Docker Image
        run: |
          docker tag yann-fan:latest 343218180642.dkr.ecr.us-east-1.amazonaws.com/yann-fan:latest

      # Push the Docker image to Amazon ECR
      - name: Push Docker Image to ECR
        run: |
          docker push 343218180642.dkr.ecr.us-east-1.amazonaws.com/yann-fan:latest

      # Deploy the Docker image to AWS Lambda
      - name: Deploy Docker Image to Lambda
        run: |
          aws lambda update-function-code \
            --function-name Yann-Fan-Backend-Lambda \
            --image-uri 343218180642.dkr.ecr.us-east-1.amazonaws.com/yann-fan:latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1